### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by paulsamaroo** [tonyvu2014/android-shoppingcart#8] opened 2016-05-26 04:10 UTC
Hey...I sometimes get an out of memory error in ProductActivity class on the following line:
ivProductImage.setImageResource(this.getResources().getIdentifier(product.getImageName(), "drawable", this.getPackageName()));

it happens when i click a product on the main activity list view.

**Comment by tonyvu2014** [comment] 2016-05-26 14:49
maybe the picture is too large

**Comment by paulsamaroo** [comment] 2016-05-26 15:38
Yes you're probably right...but also I went ahead and finish(); the previous class to save on resources. This also helped a lot.

Another thing, do you know how to format the 0's in the CartHelper.getCart(); ? I notices that if I have something like 4.00, it'll show up as 4.00000000.

Also, is there a way to add a "$" to the beginning of the prices in the listview of main activity?

**Comment by tonyvu2014** [comment] 2016-05-29 13:36
I am not sure about the first issue. I cannot reproduce it. 4.00 was just shown as 4.00000000 for me. Anyway if you want to restrict to only 2 decimal places, you should apply setScale(2, BigDecimal.ROUND_HALF_UP) on the price since price type is BigDecimal.

"$" can be easily added in.

I have committed both the changes above.

**Comment by paulsamaroo** [comment] 2016-05-29 23:58
Sorry...I meant like this...if I want to get the data which someone ordered, then I would use : 

```
            CartHelper.getCart());
```

However, when I do that, it doesn't show up with 4.00, it shows up with 4.000000
Also, $ is not shown here either. 

I've tried messing with %f and %d in Cart.java, but not succeeding. Thank you so much for your help! You are really amazing

**Comment by paulsamaroo** [comment] 2016-05-30 00:05
I went ahead and added in the $ fine, but still...can't figure out how to fix the multiple 0's in cart.java...unless i'm pulling the data from the wrong place?

strBuilder.append(String.format("Total Quantity: %d \nTotal Price: " + "$" + "%f", totalQuantity, totalPrice));

**Comment by tonyvu2014** [comment] 2016-05-30 02:41
@paulsamaroo price type is BigDecimal, so you should use setScale() to set the precision. So something like this should do:

`String.valueOf(totalPrice.setScale(2, BigDecimal.ROUND_HALF_UP))`

**Closed as completed** 2016-06-17 18:48 UTC
