### ISSUE TITLE
How to add same product twice with different attributes

### ISSUE THREAD

**Issue by siddharth2824** [tonyvu2014/android-shoppingcart#4] opened 2016-04-29 11:09 UTC
Hello @tonyvu2014 , i just integrated your library with my project and yes it's really cool , i enjoyed the code and the way you manage the whole process , but as per my requirement , i am just trying to add same product in my cart list having different attribute but is unable to add , i tried alot but it seems i am confused with your one condition can you please help me to understand the point , What i simply want to do is , suppose i am having one product on my screen having multiple color and sizes , so **at first i add the product to my cart with color Blue and size XS** and now **i am trying to add same product with Color Black and Size S or Color Blue but this time having Size M** , your library do not let me to add same product twice  , can you please tell me that what should i do to achieve this As this is very basic feature for every shoping cart.

Here is my code :- 

`public void add(final Saleable sellable, int quantity) {

```
    if (cartItemMap.containsKey(sellable)) {
        mConfigSelectedObject = sellable.getConfigurableselectedArray();
        Cart cartget = CartHelper.getCart();
        List<CartItem> cartlist = getCartItems(cartget);

        if (mConfigSelectedObject.length() > 0) {
            if (isEqualArray(cartlist, mConfigSelectedObject)) {
                cartItemMap.put(sellable, cartItemMap.get(sellable)
                        + quantity);
            } else {
                cartItemMap.put(sellable, quantity);
            }
        } else {
            cartItemMap.put(sellable, cartItemMap.get(sellable) + quantity);
        }
    } else {
        cartItemMap.put(sellable, quantity);
    }
    configurableparamArray = sellable.getConfig();
    totalPrice = totalPrice.add(sellable.getPrice().multiply(
            BigDecimal.valueOf(quantity)));
    totalQuantity += quantity;
}

private boolean isEqualArray(List<CartItem> cartlist,
        JSONArray mConfigSelectedObject2) {
    boolean isEqual = false;
    for (int i = 0; i < cartlist.size(); i++) {
        for (int j = 0; j < cartlist.get(i).getProduct()
                .getConfigurableselectedArray().length(); j++) {
            try {
                if (cartlist
                        .get(i)
                        .getProduct()
                        .getConfigurableselectedArray()
                        .getJSONObject(j)
                        .getString(Constants.KEY_ATTRIBUTE_ID)
                        .equalsIgnoreCase(
                                mConfigSelectedObject2.getJSONObject(j)
                                        .getString(
                                                Constants.KEY_ATTRIBUTE_ID))
                        && cartlist
                                .get(i)
                                .getProduct()
                                .getConfigurableselectedArray()
                                .getJSONObject(j)
                                .getString(Constants.KEY_OPTION_ID)
                                .equalsIgnoreCase(
                                        mConfigSelectedObject2
                                                .getJSONObject(j)
                                                .getString(
                                                        Constants.KEY_OPTION_ID))) {
                    isEqual = true;
                } else {
                    isEqual = false;
                }
            } catch (JSONException e) {
                e.printStackTrace();
            }

        }

    }
    mConfigSelectedObject = new JSONArray();
    return isEqual;
}`
```

As you are the master of this library , so it will be easy for you to tell me what should i do with `cartItemMap.containsKey(sellable)`

Thanks

**Comment by tonyvu2014** [comment] 2016-04-30 04:16
Hi @siddharth2824 

Thank you for using this library. To answer your question, since my library uses HashMap for shopping cart, it must be able to differentiate between different products by hashCode. That's why in my README, i mentioned that you should extend Saleable interface and override equals() and hashCode() methods. In your case, the hashCode() implementation needs to make use of product attributes (size, color,...). You can find an example of Product class under demo directory here:

https://github.com/tonyvu2014/android-shoppingcart/blob/master/demo/src/main/java/com/android/tonyvu/sc/demo/model/Product.java

There are also a lot of online examples on how to create a efficient hashCode() method.

Let me know if you still have some questions.

**Comment by siddharth2824** [comment] 2016-04-30 04:50
Thank you for your reply , so should i do something like this 

`import java.io.Serializable;
import java.math.BigDecimal;

import org.json.JSONArray;
import org.json.JSONObject;

import com.mss.magentomobileshop.basecart.Saleable;

public class Product implements Saleable, Serializable {
    private static final long serialVersionUID = -4073256626483275668L;

```
private int pId;
private String pName;
private String image;
private BigDecimal pPrice;
private String pDescription;
private String CongiurableParamArray;
private String CustomParamArray;
private JSONObject customSelectedObject;
private JSONArray configurableSelectedArray;

public Product() {
    super();
}

public Product(int pId, String pName, BigDecimal pPrice,
        String CongiurableParamArray, String CustomParamArray,
        JSONObject customSelectedObject,
        JSONArray configurableSelectedObject, String Image) {
    setId(pId);
    setName(pName);
    setPrice(pPrice);
    setCongiurableParamArray(CongiurableParamArray);
    setCustomParamArray(CustomParamArray);
    setCustomSelectedObject(customSelectedObject);
    setConfigurableSelectedObject(configurableSelectedObject);
    setImage(Image);
}

@Override
public boolean equals(Object o) {
    if (o == null)
        return false;
    if (!(o instanceof Product))
        return false;

    return (this.configurableSelectedArray == ((Product) o)
            .getConfigurableselectedArray());
}

public int hashCode() {
    final int prime = 31;
    int hash = 1;
    hash = hash * prime + pId;
    hash = hash * prime + (pName == null ? 0 : pName.hashCode());
    hash = hash * prime + (pPrice == null ? 0 : pPrice.hashCode());
    hash = hash * prime
            + (pDescription == null ? 0 : pDescription.hashCode());
    hash = hash
            * prime
            + (configurableSelectedArray == null ? 0
                    : configurableSelectedArray.hashCode());

    return hash;
}

public void setCongiurableParamArray(String congiurableParamArray) {
    CongiurableParamArray = congiurableParamArray;
}

public int getId() {
    return pId;
}

public void setId(int id) {
    this.pId = id;
}

@Override
public BigDecimal getPrice() {
    return pPrice;
}

@Override
public String getName() {
    return pName;
}

public void setPrice(BigDecimal price) {
    this.pPrice = price;
}

public void setName(String name) {
    this.pName = name;
}

public String getDescription() {
    return pDescription;
}

public void setDescription(String pDescription) {
    this.pDescription = pDescription;
}

public void setCustomParamArray(String customParamArray) {
    CustomParamArray = customParamArray;
}

public void setCustomSelectedObject(JSONObject customSelectedObject) {
    this.customSelectedObject = customSelectedObject;
}

public void setConfigurableSelectedObject(
        JSONArray configurableSelectedArray) {
    this.configurableSelectedArray = configurableSelectedArray;
}

@Override
public String getConfig() {
    // TODO Auto-generated method stub
    return CongiurableParamArray;
}

@Override
public String getCustom() {
    // TODO Auto-generated method stub
    return CustomParamArray;
}

@Override
public JSONArray getConfigurableselectedArray() {
    // TODO Auto-generated method stub
    return configurableSelectedArray;
}

@Override
public JSONObject getCustomeselectedObject() {
    // TODO Auto-generated method stub
    return customSelectedObject;
}

public void setImage(String image) {
    this.image = image;
}

@Override
public String getImage() {
    // TODO Auto-generated method stub
    return image;
}
```

}
`

**Comment by tonyvu2014** [comment] 2016-04-30 08:33
Hi @siddharth2824 

What is configurableSelectedArray? Where are your color and size? Why do you compare configurableSelectedArray in equals() method? Is it something that uniquely defines the product?

**Comment by siddharth2824** [comment] 2016-04-30 08:37
Yes it will be unique for all products as it contains the collection of color and size selected of product

**Comment by tonyvu2014** [comment] 2016-04-30 08:53
ok, then it might work. Have you tried to run that code? Does it work?

**Comment by siddharth2824** [comment] 2016-04-30 09:02
its adding same product separately  every time

**Comment by tonyvu2014** [comment] 2016-05-02 05:28
I suspect configurableSelectedArray.hashCode() is the same regardless of its content. Can you print out that value for different colors and sizes? If it is constant, then you have to go further by computing hashCode based on configurableSelectedArray items. Something like:

```
hash = hash
            * prime
            + (configurableSelectedArray[0] == null ? 0
                    : configurableSelectedArray[0].hashCode());
hash = hash
            * prime
            + (configurableSelectedArray[1] == null ? 0
                    : configurableSelectedArray[1].hashCode());
```

**Comment by tonyvu2014** [comment] 2017-04-19 03:11
Closing this issue because it cannot be reproduced

**Closed as completed by tonyvu2014** 2017-04-19 03:11 UTC
